name: Add issue to project

on:
  issues:
    types:
      - opened

permissions:
  id-token: write

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: thepwagner/token-action@v0.0.1
        id: token
        with:
          server: 'https://gtfo-yuiafdvuwa-uc.a.run.app'
          repositories: |
            - thepwagner-org/look-ma-no-pat
          permissions: |
            issues: read
            organization_projects: write
      - uses: actions/add-to-project@a9f041ddd462ed185893ea1024cec954f50dbe42 # tag=v0.3.0
        with:
          project-url: https://github.com/orgs/thepwagner-org/projects/4
          github-token: ${{steps.token.outputs.token}}
