name: Add issue to project

on:
  issues:
    types:
      - opened
      - reopened

permissions:
  id-token: write

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: thepwagner/token-action@7064f486c7bd204fc7ab56da53d202d2352a1dba # tag=v0.1.0
        id: token
        with:
          server: 'https://gtfo-yuiafdvuwa-uc.a.run.app'
          repositories: |
            - thepwagner-org/look-ma-no-pat
          permissions: |
            issues: read
            organization_projects: write
      - uses: actions/add-to-project@960fbad431afda394cfcf8743445e741acd19e85 # tag=v0.4.0
        with:
          project-url: https://github.com/orgs/thepwagner-org/projects/4
          github-token: ${{steps.token.outputs.token}}
