name: Add issue to project

on: push

permissions:
  id-token: write

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: thepwagner/token-action@main
        id: token
        with:
          server: 'https://gtfo-yuiafdvuwa-uc.a.run.app'
          repositories: |
            - thepwagner-org/debian-bullseye
          permissions: |
            contents: read
      - run: |
          git clone "https://x-access-token:${{steps.token.outputs.token}}@github.com/thepwagner-org/debian-bullseye.git"
          find .
